# To auto-connect to Wi-Fi
CIRCUITPY_WIFI_SSID="egg"
CIRCUITPY_WIFI_PASSWORD="verygood"

# To enable the web workflow. Change this too!
# Leave the User field blank in the browser.
CIRCUITPY_WEB_API_PASSWORD="verygood"

CIRCUITPY_WEB_API_PORT=80
CIRCUITPY_WEB_INSTANCE_NAME="EScooter Display"