"""Shared bit definitions for the unified lights board (8-bit mask)."""

FRONT_LOW_BIT = 1 << 0
FRONT_HIGH_BIT = 1 << 1
FRONT_LEFT_TURN_BIT = 1 << 2
FRONT_RIGHT_TURN_BIT = 1 << 3
REAR_TAIL_BIT = 1 << 4
REAR_BRAKE_BIT = 1 << 5
REAR_LEFT_TURN_BIT = 1 << 6
REAR_RIGHT_TURN_BIT = 1 << 7

TURN_BITS_MASK = (
  FRONT_LEFT_TURN_BIT
  | FRONT_RIGHT_TURN_BIT
  | REAR_LEFT_TURN_BIT
  | REAR_RIGHT_TURN_BIT
)
REAR_TURN_BITS_MASK = REAR_LEFT_TURN_BIT | REAR_RIGHT_TURN_BIT
REAR_LIGHTS_MASK = REAR_TAIL_BIT | REAR_BRAKE_BIT
IO_BITS_MASK = 0xFF
NON_TURN_MASK = IO_BITS_MASK ^ TURN_BITS_MASK
